# 测试配置文件
server:
  port: 8110
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
# 代码沙箱配置
codesandbox:
  type: remote # example: 示例沙箱，remote: 远程沙箱
  way: docker # original: 原生实现，docker 为 docker 实现

# 远程沙箱连接配置
auth:
  request:
    secret: Wcy0626..